export const LOBBY_ERRORS = {
  EMPTY_USERNAME: "EMPTY_USERNAME",
  EMPTY_LOBBY_ID: "EMPTY_LOBBY_ID",
  LOBBY_NOT_FOUND: "LOBBY_NOT_FOUND",
  CREATE_FAILED: "CREATE_FAILED",
  ADD_BOT_FAILED: "ADD_BOT_FAILED",
  LEAVE_FAILED: "LEAVE_FAILED",
  SERVER_ERROR: "SERVER_ERROR",
  CONNECTION_ERROR: "CONNECTION_ERROR",
  LOBBY_FULL: "LOBBY_FULL",
  PLAYERS_OFFLINE: "PLAYERS_OFFLINE",
  GAME_ALREADY_STARTED: "GAME_ALREADY_STARTED",
  NOT_FOUND: "NOT_FOUND",
} as const;

export type LobbyErrorCode = keyof typeof LOBBY_ERRORS;