version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/application"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "application"

  - package-ecosystem: "sbt"
    directory: "/wizardEngine"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "wizardEngine"