apiVersion: v1
kind: ConfigMap
metadata:
  name: wizard-config
data:
  APP_ENV: "production"
  HTTP_PORT: "5001"
  WS_PORT: "5002"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  APPLICATION_PORT: "3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: wizard-secrets
type: Opaque
stringData:
  REDIS_PASSWORD: "admin"
