package io.github.pallax03.wizard.engine.model.core

import scala.language.postfixOps

import io.github.pallax03.wizard.engine.model.basic.*
import io.github.pallax03.wizard.engine.model.basic.bidding.{Bid, Bids, Tricks}
import io.github.pallax03.wizard.engine.model.basic.cards.*
import io.github.pallax03.wizard.engine.model.basic.gameplay.*
import io.github.pallax03.wizard.engine.model.core.state.{
  GameState,
  ServerCoreState,
  ServerGameState
}
import io.github.pallax03.wizard.engine.model.events.*
import io.github.pallax03.wizard.engine.model.rules.*

/**
 * Purely functional core engine coordinating the Wizard game state machine and event emissions.
 *
 * Implemented as an opaque type over `(ServerGameState, List[WizardEvent])`.
 * Each state transition consumes an authoritative [[ServerGameState]] and an incoming [[GameAction]],
 * yielding either a rejected [[GameActionError]] or a new `GameEngine` tuple containing the updated state
 * and all resulting [[WizardEvent]]s.
 */
opaque type GameEngine = (ServerGameState, List[WizardEvent])

/** Companion object and state transition entry points for [[GameEngine]]. */
object GameEngine:
  extension (state: ServerGameState)
    private def toGameEngine(event: WizardEvent): GameEngine = (state, List(event))
    private def toGameEngine(events: WizardEvent*): GameEngine = (state, events.toList)
  extension (flow: GameEngine)
    /** The authoritative server game state after the transition. */
    def state: ServerGameState = flow._1

    /** The sequence of domain events generated by the transition. */
    def events: List[WizardEvent] = flow._2

    private def prepend(event: WizardEvent): GameEngine = (flow.state, event +: flow.events)

  /**
   * Initializes a brand-new Wizard game for the given players.
   *
   * Creates the initial scoreboard, starts Round 1, deals cards from a fresh deck,
   * sets the first dealer, and generates initial lifecycle and dealing events.
   *
   * @param playersIds the list of players participating in the match.
   * @return a [[GameEngine]] containing the initial state and starting events.
   * @throws GameException if internal setup invariants fail.
   */
  def initializeGame(playersIds: List[PlayerId]): GameEngine =
    val initialRound = Round.start
    val initialCore = ServerCoreState.initialize(playersIds, initialRound)
    setupNewRound(initialRound, initialCore).prepend(LifecycleEvent.GameStarted(playersIds))

  /**
   * Recovers a round by reinitializing it with the provided server core state.
   *
   * Resets hands and draws a new trump from a fresh deck while preserving cumulative scores and round progress.
   *
   * @param core the persistent core state to resume from.
   * @return a [[GameEngine]] representing the re-initialized round.
   */
  def recoverRound(core: ServerCoreState): GameEngine =
    setupNewRound(core.round, core)

  /**
   * Main state machine entry point: processes a player's action against the current state.
   *
   * Validates the action against turn order and game rules, advancing the game state
   * and emitting corresponding domain events.
   *
   * @param state  the current authoritative [[ServerGameState]].
   * @param action the incoming [[GameAction]] performed by a player.
   * @return `Right(engine)` with the updated state and emitted events if valid,
   *         or `Left(error)` containing a [[GameActionError]] if rejected by rules.
   * @throws GameException if fatal internal state inconsistencies are detected.
   */
  def processAction(
      state: ServerGameState,
      action: GameAction
  ): Either[GameActionError, GameEngine] =
    state match
      case currentState @ GameState.ChoosingTrump(_) =>
        action match
          case GameAction.ResolveTrumpColor(playerId, color) =>
            handleResolveTrump(currentState, playerId, color)
          case _ => Left(GameActionError.InvalidAction(state.pendingInvitation(action.playerId)))

      case currentState @ GameState.Bidding(_, _, _) =>
        action match
          case GameAction.PlaceBid(playerId, bid) => handlePlaceBid(currentState, playerId, bid)
          case _ => Left(GameActionError.InvalidAction(state.pendingInvitation(action.playerId)))

      case currentState @ GameState.Playing(_, _, _, _, _) =>
        action match
          case GameAction.PlayCard(playerId, card) => handlePlayCard(currentState, playerId, card)
          case _ => Left(GameActionError.InvalidAction(state.pendingInvitation(action.playerId)))

      case _ => Left(GameActionError.InvalidAction(state.pendingInvitation(action.playerId)))

  private def handlePlayCard(
      currentState: GameState.Playing[ServerCoreState],
      playerId: PlayerId,
      card: Card
  ): Either[GameActionError, GameEngine] =
    for
      _ <- currentState.playerTurn.validateTurnOf(playerId)
      playerHand = currentState.core.hands.getHand(playerId)
      _ <- card.validateAgainst(currentState.table, playerHand)
    yield
      val updatedHands = currentState.core.hands.remove(playerId, card)
      val updatedCore = currentState.core.copy(hands = updatedHands)
      val updatedTable = currentState.table + (playerId, card)

      val flow =
        if updatedTable.isTrickComplete(updatedCore.playersIds.size) then
          completeTrick(currentState, updatedCore, updatedTable)
        else advanceRegularTurn(currentState, updatedCore, updatedTable, playerId)
      flow.prepend(
        ActionEvent.CardPlayed(
          playerId,
          card,
          updatedTable.evaluateTrick(currentState.core.trump),
          updatedTable.followingColor
        )
      )

  private def advanceRegularTurn(
      currentState: GameState.Playing[ServerCoreState],
      updatedCore: ServerCoreState,
      updatedTable: Table,
      currentPlayerId: PlayerId
  ): GameEngine =
    val nextPlayer =
      currentState.core.playersIds
        .nextAfter(currentPlayerId)

    val nextHand = updatedCore.hands.getHand(nextPlayer)
    currentState
      .copy(
        core = updatedCore,
        table = updatedTable,
        playerTurn = nextPlayer
      )
      .toGameEngine(
        ProgressEvent.TurnOf(nextPlayer, GameAction.PlayCard.toString),
        InvitationEvent.WaitingForCard(
          nextPlayer,
          nextHand.legalCards(updatedTable),
          updatedTable.playedCards.isEmpty
        )
      )

  private def handlePlaceBid(
      currentState: GameState.Bidding[ServerCoreState],
      playerId: PlayerId,
      bid: Bid
  ): Either[GameActionError, GameEngine] =
    for
      _ <- currentState.playerTurn.validateTurnOf(playerId)
      updatedBids <- BiddingRules.processBid(
        bid,
        currentState.bids,
        playerId,
        currentState.core.round,
        currentState.core.playersIds.size
      )
    yield
      val flow =
        if updatedBids.isComplete(currentState.core.playersIds.size) then
          advanceToPlayingPhase(currentState, updatedBids)
        else advanceToNextBidder(currentState, updatedBids, playerId)
      flow.prepend(ActionEvent.BidPlaced(playerId, bid))

  private def advanceToPlayingPhase(
      currentState: GameState.Bidding[ServerCoreState],
      completedBids: Bids
  ): GameEngine =
    val firstPlayer = currentState.core.round.firstPlayer(currentState.core.playersIds)
    val hand = currentState.core.hands.getHand(firstPlayer)
    if hand.isEmpty then throw GameException.CorruptedHand(firstPlayer)

    GameState
      .Playing(
        core = currentState.core,
        bids = completedBids,
        table = Table.empty,
        playerTurn = firstPlayer,
        tricksWon = Tricks.empty
      )
      .toGameEngine(
        ProgressEvent.PhaseChanged(GameState.Playing.toString),
        ProgressEvent.TurnOf(firstPlayer, GameAction.PlayCard.toString),
        InvitationEvent.WaitingForCard(firstPlayer, hand.legalCards(Table.empty), true)
      )

  private def advanceToNextBidder(
      currentState: GameState.Bidding[ServerCoreState],
      updatedBids: Bids,
      currentPlayerId: PlayerId
  ): GameEngine =
    val nextPlayer =
      currentState.core.playersIds.nextAfter(currentPlayerId)
    currentState
      .copy(
        bids = updatedBids,
        playerTurn = nextPlayer
      )
      .toGameEngine(
        ProgressEvent.TurnOf(nextPlayer, GameAction.PlaceBid.toString),
        InvitationEvent.WaitingForBid(
          nextPlayer,
          currentState.core.round,
          updatedBids.notValidBid(currentState.core.round, currentState.core.playersIds.size)
        )
      )

  private def handleResolveTrump(
      currentState: GameState.ChoosingTrump[ServerCoreState],
      playerId: PlayerId,
      color: Card.Color
  ): Either[GameActionError, GameEngine] =
    for
      _ <- currentState.core.dealerId.validateTurnOf(playerId)
      updatedTrump <- currentState.core.trump resolveWizard color
    yield
      val trumpResolvedEvent = ActionEvent.TrumpColorResolved(playerId, color)
      advanceToBiddingPhase(currentState, updatedTrump, trumpResolvedEvent)

  private def advanceToBiddingPhase(
      currentState: GameState.ChoosingTrump[ServerCoreState],
      updatedTrump: Trump,
      trumpResolvedEvent: ActionEvent.TrumpColorResolved
  ): GameEngine =
    GameState
      .Bidding(
        currentState.core.updateTrump(updatedTrump),
        Bids.empty,
        currentState.core.dealerId
      )
      .toGameEngine(
        trumpResolvedEvent,
        ProgressEvent.PhaseChanged(GameState.Bidding.toString),
        ProgressEvent.TurnOf(currentState.core.dealerId, GameAction.PlaceBid.toString),
        InvitationEvent.WaitingForBid(
          currentState.core.dealerId,
          currentState.core.round,
          Bids.empty.notValidBid(currentState.core.round, currentState.core.playersIds.size)
        )
      )

  private def completeTrick(
      state: GameState.Playing[ServerCoreState],
      updatedCore: ServerCoreState,
      completedTable: Table
  ): GameEngine =
    val winningCard = completedTable
      .evaluateTrick(updatedCore.trump)
      .getOrElse(throw GameException.TableNoWinner)

    val winnerId = completedTable
      .playerOf(winningCard)

    val updatedTricks = state.tricksWon addTrickTo winnerId

    val flow =
      if isRoundComplete(updatedCore.hands) then completeRound(state, updatedCore, updatedTricks)
      else advanceToNextTrickTurn(state, updatedCore, updatedTricks, winnerId)
    flow.prepend(
      ProgressEvent.TrickWon(
        winnerId,
        updatedTricks(winnerId),
        completedTable.playedCards
      )
    )

  private def isRoundComplete(hands: Hands): Boolean = hands.areEmpty

  private def advanceToNextTrickTurn(
      state: GameState.Playing[ServerCoreState],
      updatedCore: ServerCoreState,
      updatedTricks: Tricks,
      winnerId: PlayerId
  ): GameEngine =
    state
      .copy(
        core = updatedCore,
        table = Table.empty,
        playerTurn = winnerId,
        tricksWon = updatedTricks
      )
      .toGameEngine(
        ProgressEvent.TurnOf(winnerId, GameAction.PlayCard.toString),
        InvitationEvent
          .WaitingForCard(
            winnerId,
            updatedCore.hands.getHand(winnerId).legalCards(Table.empty),
            true
          )
      )

  private def completeRound(
      state: GameState.Playing[ServerCoreState],
      updatedCore: ServerCoreState,
      updatedTricks: Tricks
  ): GameEngine =
    val updatedScoreboard = ScoringRules.compute(
      updatedCore.playersIds,
      state.bids,
      updatedTricks,
      updatedCore.round,
      updatedCore.scoreboard
    )
    nextRoundOrEnd(updatedCore.copy(scoreboard = updatedScoreboard))
      .prepend(ProgressEvent.RoundScored(updatedCore.playersIds, updatedScoreboard))

  private def nextRoundOrEnd(core: ServerCoreState): GameEngine =
    if core.round.isLastRound(core.playersIds) then
      GameState
        .Ended(core.playersIds, core.scoreboard)
        .toGameEngine(LifecycleEvent.GameEnded(core.playersIds, core.scoreboard))
    else
      val nextRound = core.round.next
      val nextDealer = core.playersIds.nextAfter(core.dealerId)
      setupNewRound(nextRound, core.copy(round = nextRound, dealerId = nextDealer))

  private def setupNewRound(
      round: Round,
      coreContext: ServerCoreState
  ): GameEngine =
    val (newCore, gameState) = round.initialize(Deck.create).run(coreContext).value

    val invitationEvents: List[WizardEvent] = gameState match
      case GameState.ChoosingTrump(_) =>
        List(
          ProgressEvent.TurnOf(newCore.dealerId, GameAction.ResolveTrumpColor.toString),
          InvitationEvent.WaitingForTrump(newCore.dealerId)
        )
      case GameState.Bidding(_, _, playerTurn) =>
        List(
          ProgressEvent.TurnOf(playerTurn, GameAction.PlaceBid.toString),
          InvitationEvent.WaitingForBid(
            playerTurn,
            round,
            Bids.empty.notValidBid(round, newCore.playersIds.size)
          )
        )
      case _ => List.empty

    val cardsDeals: List[WizardEvent] = newCore.playersIds.map: pId =>
      ProgressEvent.CardsDealt(pId, newCore.hands.getHand(pId), newCore.trump, newCore.round)

    val allEvents =
      cardsDeals ::: ProgressEvent.PhaseChanged(gameState.productPrefix) :: invitationEvents
    gameState.toGameEngine(allEvents*)
