rules = [
  RemoveUnused,
  OrganizeImports,
  ExplicitResultTypes,
  TypelevelMapSequence,
  TypelevelAs
]

OrganizeImports {
  targetDialect = Scala3
  groupedImports = Merge
  groups = [
    "re:javax?\\.",
    "scala.",
    "cats.",
    "io.circe.",
    "io.vertx.",
    "io.github.pallax03.wizard.",
    "*"
  ]
  removeUnused = true
  expandRelative = true
  importsOrder = Ascii
  blankLines = Auto
}
runner.dialect = scala3
